#!/usr/bin/env bash
#
# measure.sh — the after-snapshot. Recomputes metrics post-merge and diffs against baseline.json,
# writing impact.json + a human-readable scorecard.md (before | after | Δ | class).
#
# This is the final autopilot phase, "measure-impact". Deterministic rows are the honest headline;
# empirical rows carry their sample basis. Read-only w.r.t. repo source.
#
# Deps: bash, jq; optional: cargo, gh, git. Reuses baseline.sh to compute the "after" snapshot.
# Usage: measure.sh [repo_root]

set -euo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT"
OUT_DIR="$ROOT/.optimizer"
BASELINE="$OUT_DIR/baseline.json"
IMPACT="$OUT_DIR/impact.json"
SCORECARD="$OUT_DIR/scorecard.md"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -f "$BASELINE" ]; then
  echo "error: no baseline at $BASELINE — run baseline.sh before optimizing." >&2
  exit 1
fi

# Recompute the current snapshot by reusing baseline.sh, capturing only its JSON (stdout).
AFTER_JSON=$(bash "$SCRIPT_DIR/baseline.sh" "$ROOT" 2>/dev/null)

# Build impact.json: pair each metric's before/after and compute the delta.
jq -n \
  --slurpfile before "$BASELINE" \
  --argjson after "$AFTER_JSON" \
  '
  ($before[0]) as $b |
  def num(x): if (x|type)=="number" then x else null end;
  def delta(a; b): if (a|type)=="number" and (b|type)=="number" then (b - a) else null end;
  {
    generated_by: "rust-optimizer/measure.sh",
    root: $b.root,
    metrics: [
      {name:"cargo_lock_lines", class:"deterministic",
       before: $b.deterministic.cargo_lock_lines, after: $after.deterministic.cargo_lock_lines,
       delta: delta($b.deterministic.cargo_lock_lines; $after.deterministic.cargo_lock_lines)},
      {name:"direct_deps", class:"deterministic",
       before: $b.deterministic.direct_deps, after: $after.deterministic.direct_deps,
       delta: delta($b.deterministic.direct_deps; $after.deterministic.direct_deps)},
      {name:"full_workspace_compiles_per_pr", class:"deterministic",
       before: $b.deterministic.full_workspace_compiles_per_pr, after: $after.deterministic.full_workspace_compiles_per_pr,
       delta: delta($b.deterministic.full_workspace_compiles_per_pr; $after.deterministic.full_workspace_compiles_per_pr)},
      {name:"enforced_gates", class:"deterministic",
       before: $b.deterministic.enforced_gates, after: $after.deterministic.enforced_gates,
       delta: delta($b.deterministic.enforced_gates; $after.deterministic.enforced_gates)},
      {name:"setup_qemu_present", class:"deterministic",
       before: $b.deterministic.setup_qemu_present, after: $after.deterministic.setup_qemu_present,
       delta: null},
      {name:"unused_deps", class:"deterministic",
       before: $b.deterministic.unused_deps, after: $after.deterministic.unused_deps,
       delta: delta($b.deterministic.unused_deps; $after.deterministic.unused_deps)},
      {name:"median_time_to_green_seconds", class:"empirical",
       before: $b.empirical.median_time_to_green_seconds, after: $after.empirical.median_time_to_green_seconds,
       delta: delta($b.empirical.median_time_to_green_seconds; $after.empirical.median_time_to_green_seconds),
       basis: ("before: "+($b.empirical.note)+"; after: "+($after.empirical.note))}
    ]
  }' | tee "$IMPACT" >/dev/null

# Render scorecard.md from impact.json.
{
  echo "# Optimization Scorecard"
  echo
  echo "Generated by rust-optimizer/measure.sh. Deterministic rows are exact; empirical rows carry their sample basis."
  echo
  echo "| Metric | Before | After | Δ | Class |"
  echo "| --- | --- | --- | --- | --- |"
  jq -r '.metrics[]
    | "| \(.name) | \(.before // "n/a") | \(.after // "n/a") | \(.delta // "—") | \(.class) |"' "$IMPACT"
  echo
  echo "> Empirical timing is reported only with enough warm runs on both sides; otherwise it reads \"n/a — deterministic only\"."
} >"$SCORECARD"

echo "impact written to $IMPACT" >&2
echo "scorecard written to $SCORECARD" >&2
cat "$SCORECARD"
